version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.14.0"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

conda:
  environment: docs/environment.yml