name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - sphinx==5.3.0
  - cython==0.29.32
  - llvmlite=0.39
  - numba==0.56.3
  - numpy==1.23.4
  - conda
  - pip:
    - sphinx_rtd_theme==1.1.1