name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - sphinx==5.3.0
  - numba==0.56.3
  - scipy==1.9.3
  - numpy==1.23.4
  - pylops==1.18.3
  - tqdm==4.64.1
  - pip==22.3
  - pip:
    - sphinx_rtd_theme==1.1.1
    - sphinxcontrib-bibtex==2.5.0
    - nbsphinx